# Generated by Django 5.2 on 2025-04-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('validity', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('savings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booked_count', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
