# Generated by Django 5.2 on 2025-04-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_remove_guest_check_in_date_remove_guest_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='name',
        ),
        migrations.AddField(
            model_name='guest',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(default=101, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='first_name',
            field=models.CharField(default=102, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='last_name',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(default=101, max_length=15),
            preserve_default=False,
        ),
    ]
