# Generated by Django 5.2 on 2025-04-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_remove_guest_name_guest_check_in_date_guest_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='last_name',
        ),
        migrations.AddField(
            model_name='guest',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
