# Generated by Django 5.2 on 2025-04-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_payment_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='guest',
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
